// Code/Frontend/enrollment-app/src/components/CustomerLocate.jsx
import React, { useState } from 'react'

function CustomerLocate({ formData, onNext }) {
  const [formState, setFormState] = useState({
    accountNumber: formData.accountNumber || '',
    ssn: formData.ssn || '',
    birthdate: formData.birthdate || ''
  })

  const handleInputChange = (e) => {
    const { name, value } = e.target
    setFormState(prev => ({
      ...prev,
      [name]: value
    }))
  }

  const handleSubmit = (e) => {
    e.preventDefault()
    onNext(formState)
  }

  return (
    <div className="card w-full max-w-md">
      <div className="text-center mb-6">
        <h2 className="text-2xl font-bold text-gray-900 mb-2">Account Opening</h2>
        <p className="text-gray-600">Customer Locate</p>
      </div>
      
      <form onSubmit={handleSubmit} className="space-y-4">
        <div>
          <label htmlFor="accountNumber" className="block text-sm font-medium text-gray-700 mb-2">
            Account Number
          </label>
          <input
            type="text"
            id="accountNumber"
            name="accountNumber"
            value={formState.accountNumber}
            onChange={handleInputChange}
            placeholder="Enter account number"
            className="form-input"
            required
          />
        </div>
        
        <div>
          <label htmlFor="ssn" className="block text-sm font-medium text-gray-700 mb-2">
            SSN
          </label>
          <input
            type="text"
            id="ssn"
            name="ssn"
            value={formState.ssn}
            onChange={handleInputChange}
            placeholder="Enter SSN"
            className="form-input"
            required
          />
        </div>
        
        <div>
          <label htmlFor="birthdate" className="block text-sm font-medium text-gray-700 mb-2">
            Birthdate
          </label>
          <input
            type="date"
            id="birthdate"
            name="birthdate"
            value={formState.birthdate}
            onChange={handleInputChange}
            className="form-input"
            required
          />
        </div>
        
        <button type="submit" className="btn-primary mt-6">
          Next
        </button>
      </form>
    </div>
  )
}

export default CustomerLocate

// Code/Frontend/enrollment-app-angular/src/app/components/customer-locate/customer-locate.component.ts
import { Component, Input, Output, EventEmitter, signal, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';

interface FormData {
  accountNumber: string;
  ssn: string;
  birthdate: string;
  email: string;
  username: string;
  password: string;
  confirmPassword: string;
  phoneNumber: string;
}

@Component({
  selector: 'app-customer-locate',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './customer-locate.component.html',
  styleUrl: './customer-locate.component.css'
})
export class CustomerLocateComponent implements OnInit {
  @Input() formData!: FormData;
  @Output() onNext = new EventEmitter<Partial<FormData>>();

  formState = signal({
    accountNumber: '',
    ssn: '',
    birthdate: ''
  });

  ngOnInit() {
    this.formState.set({
      accountNumber: this.formData?.accountNumber || '',
      ssn: this.formData?.ssn || '',
      birthdate: this.formData?.birthdate || ''
    });
  }

  handleInputChange(field: string, value: string) {
    this.formState.update(prev => ({
      ...prev,
      [field]: value
    }));
  }

  handleSubmit(event: Event) {
    event.preventDefault();
    this.onNext.emit(this.formState());
  }
}

<div class="card w-full max-w-md">
  <div class="text-center mb-6">
    <h2 class="text-2xl font-bold text-gray-900 mb-2">Account Opening</h2>
    <p class="text-gray-600">Customer Locate</p>
  </div>
  
  <form (submit)="handleSubmit($event)" class="space-y-4">
    <div>
      <label for="accountNumber" class="block text-sm font-medium text-gray-700 mb-2">
        Account Number
      </label>
      <input
        type="text"
        id="accountNumber"
        [value]="formState().accountNumber"
        (input)="handleInputChange('accountNumber', ($any($event.target).value))"
        placeholder="Enter account number"
        class="form-input"
        required
      />
    </div>
    
    <div>
      <label for="ssn" class="block text-sm font-medium text-gray-700 mb-2">
        SSN
      </label>
      <input
        type="text"
        id="ssn"
        [value]="formState().ssn"
        (input)="handleInputChange('ssn', ($any($event.target).value))"
        placeholder="Enter SSN"
        class="form-input"
        required
      />
    </div>
    
    <div>
      <label for="birthdate" class="block text-sm font-medium text-gray-700 mb-2">
        Birthdate
      </label>
      <input
        type="date"
        id="birthdate"
        [value]="formState().birthdate"
        (input)="handleInputChange('birthdate', ($any($event.target).value))"
        class="form-input"
        required
      />
    </div>
    
    <button type="submit" class="btn-primary mt-6">
      Next
    </button>
  </form>
</div>
