// Code/Frontend/enrollment-app/src/components/ThankYou.jsx
import React from 'react'

function ThankYou() {
  return (
    <div className="card w-full max-w-md text-center">
      <div className="mb-6">
        <div className="w-16 h-16 bg-green-100 rounded-full flex items-center justify-center mx-auto mb-4">
          <svg className="w-8 h-8 text-green-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
          </svg>
        </div>
        <h2 className="text-3xl font-bold text-gray-900 mb-2">Thank You!</h2>
        <p className="text-gray-600 text-lg">Your account has been successfully created!</p>
      </div>
      
      <div className="bg-gray-50 rounded-lg p-4 mb-6">
        <p className="text-sm text-gray-600">
          We've sent a confirmation email with your account details. 
          Please check your inbox and follow the instructions to complete your account setup, including setting up two-factor authentication.
        </p>
      </div>
      
      <button
        onClick={() => window.location.reload()}
        className="btn-primary"
      >
        Start Over
      </button>
    </div>
  )
}

export default ThankYou

// Code/Frontend/enrollment-app-angular/src/app/components/thank-you/thank-you.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-thank-you',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './thank-you.component.html',
  styleUrl: './thank-you.component.css'
})
export class ThankYouComponent {
  handleStartOver() {
    window.location.reload();
  }
}

<div class="card w-full max-w-md text-center">
  <div class="mb-6">
    <div class="w-16 h-16 bg-green-100 rounded-full flex items-center justify-center mx-auto mb-4">
      <svg class="w-8 h-8 text-green-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7"></path>
      </svg>
    </div>
    <h2 class="text-3xl font-bold text-gray-900 mb-2">Thank You!</h2>
    <p class="text-gray-600 text-lg">Your account has been successfully created!</p>
  </div>
  
  <div class="bg-gray-50 rounded-lg p-4 mb-6">
    <p class="text-sm text-gray-600">
      We've sent a confirmation email with your account details. 
      Please check your inbox and follow the instructions to complete your account setup, including setting up two-factor authentication.
    </p>
  </div>
  
  <button
    (click)="handleStartOver()"
    class="btn-primary"
  >
    Start Over
  </button>
</div>
